[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "agentic-ai"
version = "0.1.0"
description = "Agentic AI application"
requires-python = ">=3.11"
dependencies = [
    "langchain",
    "langchain-community",
    "langchain-experimental",
    "fastapi",
    "python-dotenv",
    "streamlit",
    "uvicorn",
    "pydantic",
    "httpx",
    "requests",
    "langchain-google-community",
    "langchain-tavily",
    "langchain-groq",
    "langchain-openai",
    "langgraph",
    "langchain-google-community[places]"
]

[tool.setuptools.packages.find]
where = ["."]
include = [
    "agent*",
    "config*",
    "logger*",
    "exception*",
    "prompt_library*",
    "tools*",
    "utils*"
]
exclude = [
    "notebook*",
    "tests*"
]